config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponse
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage


def empty_favicon(request):
    return HttpResponse(status=204)

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),

    path('api/', include('todo_api.urls', namespace='todo_api')),

    path('admin/', admin.site.urls),

    path('users/', include('users.urls', namespace='users')),
    path('', include('todo.urls', namespace='todo')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from todo.apps import TodoConfig
from django.urls import path
from todo.views import TaskCreate, TaskList, TaskDetail, TaskUpdate, TaskDelete, toggle_activity
from users.views import home

app_name = TodoConfig.name

urlpatterns = [
    path('', home, name='base'),
    path('task_create/', TaskCreate.as_view(), name='task_create'),
    path('todo_list/', TaskList.as_view(), name='task_list'),
    path('task_detail/<int:pk>/', TaskDetail.as_view(), name='task_detail'),
    path('task_update/<int:pk>/', TaskUpdate.as_view(), name='task_update'),
    path('task_delete/<int:pk>/', TaskDelete.as_view(), name='task_delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

todo/models.py
from django.db import models

from users.models import User


class Task(models.Model):
    name = models.CharField(max_length=40, verbose_name='Имя задачи')
    description = models.CharField(max_length=100, verbose_name='Описание задачи')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    status = models.BooleanField(default=False, verbose_name='Статус')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец', blank=True, null=True)
    deadline = models.DateField(verbose_name='Срок выполнения', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

todo/forms.py
from django.forms import ModelForm

from todo.models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'description', 'deadline',)

todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from todo.forms import TaskForm
from todo.models import Task
from django.urls import reverse_lazy, reverse

from users.models import User


class TaskCreate(CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'todo/todo_create.html'
    success_url = reverse_lazy('todo:task_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class TaskList(ListView):
    model = Task
    template_name = 'todo/todo_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)


class TaskDetail(DetailView):
    model = Task
    template_name = 'todo/todo_detail.html'


class TaskUpdate(UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'todo/todo_update.html'
    success_url = reverse_lazy('todo:task_list')


class TaskDelete(DeleteView):
    model = Task
    success_url = reverse_lazy('todo:task_list')


def toggle_activity(request, pk):
    status_item = get_object_or_404(Task, pk=pk)
    if status_item.status:
        status_item.status = False
    else:
        status_item.status = True

    status_item.save()
    return redirect(reverse_lazy('todo:task_list'))

todo/templates/todo/task_confirm_delete.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить задачу?</p>
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a href="{% url 'todo:task_list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

todo/templates/todo/todo_create.html
{% extends 'users/base.html' %}

{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn btn-primary">Регистрация</button>
</form>
{% endblock %}

todo/templates/todo/todo_detail.html
{% extends 'users/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ task.name }}</text>
                    </svg>
                    <div class="card-body">
                        <p class="card-text">{{ task.description }}</p>
                        <p class="card-text">{{ task.owner }}</p>
                        {% if task.status == False %}
                        <a class="btn btn-success" href="{% url 'todo:toggle_activity' task.pk %}">Выполнено</a>
                        {% else %}
                        <a class="btn btn-warning" href="{% url 'todo:toggle_activity' task.pk %}">Не выполнено</a>
                        {% endif %}
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">Посмотреть</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Редактировать</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Удалить</button>
                            </div>
                            <small class="text-body-secondary">{{ task.created_at }}</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

todo/templates/todo/todo_list.html
{% extends 'users/base.html' %}
{% block content %}
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Задачи</h1>
                <p class="lead text-body-secondary">Управляй делами правильно</p>
                <p>
                    <a href="{% url 'todo:task_create' %}" class="btn btn-primary my-2">Создать новую задачу</a>
<!--                    <a href="#" class="btn btn-secondary my-2">Secondary action</a>-->
                </p>
            </div>
        </div>
    </section>
</main>

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for task in task_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ task.name }}</text>
                    </svg>
                    <div class="card-body">
                        <p class="card-text">{{ task.description }}</p>
                        <p class="card-text">{{ task.owner }}</p>
                        <p class="card-text">{{ task.status }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button class="nav-item"><a href="{% url 'todo:task_detail' task.pk %}" class="nav-link">Посмотреть</a></button>
                                <button class="nav-item"><a href="{% url 'todo:task_update' task.pk %}" class="nav-link">Редактировать</a></button>
                                <button class="nav-item"><a href="{% url 'todo:task_delete' task.pk %}" class="nav-link">Удалить</a></button>
                            </div>
                            <small class="text-body-secondary">{{ task.created_at }}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

todo/templates/todo/todo_update.html
{% extends 'users/base.html' %}
{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Редактировать
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Редактировать</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}