config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponse
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage


def empty_favicon(request):
    return HttpResponse(status=204)

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),

    path('api/', include('todo_api.urls', namespace='todo_api')),

    path('admin/', admin.site.urls),

    path('users/', include('users.urls', namespace='users')),
    path('', include('todo.urls', namespace='todo')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from todo.apps import TodoConfig
from django.urls import path
from todo.views import TaskCreate, TaskList, TaskDetail, TaskUpdate, TaskDelete, toggle_activity
from users.views import home

app_name = TodoConfig.name

urlpatterns = [
    path('', home, name='base'),
    path('task_create/', TaskCreate.as_view(), name='task_create'),
    path('todo_list/', TaskList.as_view(), name='task_list'),
    path('task_detail/<int:pk>/', TaskDetail.as_view(), name='task_detail'),
    path('task_update/<int:pk>/', TaskUpdate.as_view(), name='task_update'),
    path('task_delete/<int:pk>/', TaskDelete.as_view(), name='task_delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from users.apps import UsersConfig
from users.views import home, UserCreate, UserLogin, UserDetail, UserLogout, UserUpdate, UserDelete

app_name = UsersConfig.name

urlpatterns = [
    path('create/', UserCreate.as_view(), name='create_user'),
    path('login/', UserLogin.as_view(), name='login_user'),
    path('logout/', UserLogout.as_view(), name='logout_user'),
    path('detail/<int:pk>/', UserDetail.as_view(), name='detail_user'),
    path('update/<int:pk>/', UserUpdate.as_view(), name='update_user'),
    path('delete/<int:pk>/', UserDelete.as_view(), name='delete_user'),
]

users/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Введите почту")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError("Суперпользователь должен имет статус 'is_staff'")
        if extra_fields.get('is_superuser') is not True:
            raise ValueError("Суперпользователь должен имет статус 'is_superuser'")

        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')
    city = models.CharField(max_length=100, blank=True, null=True, verbose_name='Город')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self):
        return f"{self.email}"

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'city',)

users/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView

from users.forms import UserForm
from users.models import User


def home(request):
    return render(request, 'users/base.html')


class UserCreate(CreateView):
    model = User
    form_class = UserForm
    template_name = 'users/create_user.html'
    success_url = reverse_lazy('todo:base')


class UserLogin(LoginView):
    template_name = 'users/login_user.html'
    success_url = reverse_lazy('todo:task_list')


class UserLogout(LogoutView):
    template_name = 'users/logout_user.html'
    success_url = reverse_lazy('todo:task_list')


class UserDetail(DetailView):
    model = User
    template_name = 'users/detail_user.html'


class UserUpdate(UpdateView):
    model = User
    form_class = UserForm
    template_name = 'users/update_user.html'
    success_url = reverse_lazy('detail_user')


class UserDelete(DeleteView):
    model = User
    success_url = reverse_lazy('todo:base')

users/templates/users/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
{% load static %}
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>
    <meta charset="utf-8">
    <title>Управляй задачами правильно</title>

    <link href="{% static 'css/bootstrap.min.css'%}"  rel="stylesheet">

</head>
<h1 class="visually-hidden"></h1>
<div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Задачи</span>
      </a>
      <ul class="nav nav-pills">
          {% if user.is_authenticated %}
          <li class="nav-item"><form method="post" action="{% url 'users:logout_user' %}">
              {% csrf_token %}
              <button type="submit" class="nav-link">Выход</button>

          </form></li>
          {% else %}
          <li class="nav-item"><a href="{% url 'users:login_user' %}" class="nav-link">Вход</a></li>
          <li class="nav-item"><a href="{% url 'users:create_user' %}" class="nav-link active" aria-current="page">Регистрация</a></li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item"><a href="{% url 'users:detail_user' user.pk %}" class="nav-link">Профиль</a></li>
          <li class="nav-item"><a href="{% url 'todo:task_list' %}" class="nav-link">Задачи</a></li>
          {% endif %}
        <li class="nav-item"><a href="#" class="nav-link">О нас</a></li>
        <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
      </ul>
    </header>
  </div>
<body>

{% block content %}
{% endblock %}
<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Подняться наверх</a>
        </p>
        <p class="mb-1">На этом сайте вы можете управлять своими задачами</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}">

</script>

</body>
</html>

users/templates/users/create_user.html
{% extends 'users/base.html' %}
{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Регистрация
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Регистрация</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/detail_user.html
{% extends 'users/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ user.name }}</text>
                    </svg>
                    <div class="card-body">
                        <p class="card-text">{{ user.email }}</p>
                        <p class="card-text">{{ user.city }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <ul class="nav nav-pills">
                                <li class="nav-item"><a href="{% url 'users:update_user' user.pk %}" class="nav-link">Редактировать</a></li>
                                <li class="nav-item"><a href="{% url 'users:delete_user' user.pk %}" class="nav-link">Удалить</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/login_user.html
{% extends 'users/base.html' %}
{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Регистрация
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Регистрация</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/logout_user.html
{% extends 'users/base.html' %}

users/templates/users/update_user.html
{% extends 'users/base.html' %}
{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Регистрация
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Регистрация</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить пользователя?</p>
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a href="{% url 'todo:task_list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}